Ventas_Vehiculos/Ventas_Vehiculos/Controllers/ModelosController.cs
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Ventas_Vehiculos.Models;

namespace Ventas_Vehiculos.Controllers
{
    public class ModelosController : Controller
    {
        private DB_VehiculosEntities3 db = new DB_VehiculosEntities3();
        // GET: Modelos
        public ActionResult Index()
        {
            return View(db.TBL_Modelo.ToList());
        }

        // GET: Modelos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            TBL_Modelo modelo = db.TBL_Modelo.Find(id);
            if (modelo == null)
            {
                return HttpNotFound();
            }
            return View(modelo);
        }



		[HttpGet]
		public ActionResult Index(int? page, string searchText)
		{

			int pageSize = 10;
			int pageNumber = (page ?? 1);
			ViewBag.PageNumber = pageNumber;
			IEnumerable<TBL_Modelo> modelos;

			modelos = db.TBL_Modelo.AsQueryable();

			if (!string.IsNullOrEmpty(searchText))
			{
				modelos = modelos.Where(m => m.TC_Descripcion.Contains(searchText));
			}
			int totalItems = modelos.Count(); // Cantidad total de elementos
			int totalPages = (int)Math.Ceiling((double)totalItems / pageSize); // Cálculo de total de páginas
			ViewBag.totalPages = totalPages;

			ViewBag.CurrentFilter = searchText;

			var modelosOrdenadas = modelos.OrderBy(m => m.TC_Descripcion);
			var modelosPaginas = modelosOrdenadas.Skip((pageNumber - 1) * pageSize).Take(pageSize);


			return View(modelosPaginas);
			//return View(marcasOrdenadas.ToList());
			// Paginate the marcas

		}


		// GET: Modelos/Create
		public ActionResult Create()
        {
            return View();
        }

        // POST: Modelos/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "TN_idModelo, TC_Descripcion")] TBL_Modelo modelo)
        {
            if (ModelState.IsValid)
            {
                db.TBL_Modelo.Add(modelo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(modelo);

        }

        // GET: Modelos/Edit/5
        public ActionResult Edit(int? id)
        {
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			TBL_Modelo modelo = db.TBL_Modelo.Find(id);
			if (modelo == null)
			{
				return HttpNotFound();
			}
			return View(modelo);
		}

        // POST: Modelos/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "TN_idModelo, TC_Descripcion")] TBL_Modelo modelo)
        {
			if (ModelState.IsValid)
			{
				db.Entry(modelo).State = EntityState.Modified;
                db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(modelo);
		}

        // GET: Modelos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Modelos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Modelos/Create.cshtml
@model Ventas_Vehiculos.Models.TBL_Modelo

@{
	ViewBag.Title = "Nuevo modelo";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />

<h2 class="titulo_create">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal letra_tabla">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group ">
			<label class="titulo_details_tabla letra_search control-label col-md-2">Modelo</label>
			<div class="col-md-10">
				@Html.EditorFor(model => model.TC_Descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe modelo", @required = true } })
				@Html.ValidationMessageFor(model => model.TC_Descripcion, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button type="submit" class="btn btn-secondary btn_create">
					<i class="fa fa-plus"></i>
					
				</button>
			</div>
		</div>
	</div>
}

<div>
	<a class="estilo_boton_lista btn btn-secondary" href="@Url.Action("Index", "Modelos")">
		<i class="fa fa-undo" aria-hidden="true"></i>
		

	</a>
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Modelos/Details.cshtml
@model Ventas_Vehiculos.Models.TBL_Modelo

@{
    ViewBag.Title = "Detalles modelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="titulo_details">@ViewBag.Title</h2>

<div>
	<hr />
	<dl class="dl-horizontal letra_tabla letra_search">
		<dt class="titulo_details_tabla">
			Modelo
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TC_Descripcion)
			
		</dd>

	</dl>
</div>
<p>
	<a class="btn btn-secondary editar btn-separator" href="@Url.Action("Edit","Modelos",  new { id = Model.TN_IdModelo } )">
		<i class="fa-solid fa-pen-to-square">

		</i>
	
	</a>

	<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Modelos", new { id = Model.TN_IdModelo})">
		<i class="fa fa-undo"></i>
		
	</a>
</p>

Ventas_Vehiculos/Ventas_Vehiculos/Views/Modelos/Edit.cshtml
@model Ventas_Vehiculos.Models.TBL_Modelo

@{
	ViewBag.Title = "Actualizando modelo";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="titulo_edit">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal letra_form">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.TN_IdModelo)

		<div class="form-group letra_search">
			<label class="titulo_details_tabla control-label col-md-2"> Modelo</label>
			<div class="col-md-10">
				@Html.EditorFor(model => model.TC_Descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe modelo", @required = true } })
				<br />
				@Html.ValidationMessageFor(model => model.TC_Descripcion, "Completa este campo", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button type="submit" class="btn btn-secondary editar">
					<i class="fa fa-refresh" aria-hidden="true"></i>
					
				</button>
			</div>
		</div>
	</div>
}

<div>
	<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Modelos")">
		<i class="fa fa-undo"></i>
		
	</a>
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Modelos/Index.cshtml
@model IEnumerable<Ventas_Vehiculos.Models.TBL_Modelo>
@using PagedList
@using PagedList.Mvc

@{
	ViewBag.Title = "Modelos";
	Layout = "~/Views/Shared/_Layout.cshtml";
	ViewBag.CurrentFilter = ViewBag.CurrentFilter ?? "";
}

<h2 class="titulo_index">@ViewBag.Title</h2>

<p>
	<a class="btn btn-secondary btn_create" href="@Url.Action("Create","Modelos")">
		<i class="fa fa-plus" aria-hidden="true"></i>

	</a>
</p>

@using (Html.BeginForm("Index", "Modelos", FormMethod.Get))
{
	<div class="form-group letra_search">
		@Html.Label("Filtrar por modelo")
		@Html.TextBox("searchText", ViewBag.CurrentFilter as string, new { @class = "form-control", @required = true, @placeholder = "Escribe modelo" })
		<button type="submit" class="btn btn-secondary btn_search btn-separator">
			<i class="fa-solid fa-search"></i>
		</button>
		<a href="@Url.Action("Index", "Modelos")" class="btn btn-secondary btn_clean ">
			<i class="fa-solid fa-eraser"></i>
		</a>
	</div>
}

<div class="table-responsive">
	<div class="cuadro_tabla">
		<table class="table letra_tabla table-bordered table-hover">

			<tr class="titulo_encabezado_tabla">
				<th class="titulo_encabezado_tabla">
					Modelos
				</th>
				<th class="titulo_encabezado_tabla" colspan="2">
					Operaciones
				</th>
			</tr>
			<tbody class="table letra_tabla table-bordered table-hover">
				@foreach (var item in Model)
				{
					<tr class="datos_tabla table-hover">
						<td>
							@Html.DisplayFor(modelItem => item.TC_Descripcion)
						</td>
						<td>
							<div class="btn-group" role="group">
								<a class="btn btn-secondary editar btn-separator"
								   href="@Url.Action("Edit", "Modelos", new { id = item.TN_IdModelo })">
									<i class="fa-solid fa-pen-to-square"></i>
								</a>
								<a class="btn btn-secondary detallado btn-separator"
								   href="@Url.Action("Details", "Modelos", new { id = item.TN_IdModelo })">
									<i class="fa-solid fa-circle-info"></i>
								</a>
							</div>
						</td>
					</tr>
				}
			</tbody>
		</table>
	</div>
</div>


<!-- Resto del código anterior -->
@if (ViewBag.CurrentFilter != null && Model.Any())
{

}

@if (Model.Any())
{
	<div class="current-page-info datos_paginacion">
		Página @ViewBag.PageNumber de @ViewBag.totalPages
	</div>
}

<div class="pagination-container datos_paginacion">
	@if (Model.Any())
	{
		<ul class="pagination">
			@if (ViewBag.PageNumber > 1)
			{
				if (ViewBag.CurrentFilter != null)
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.PageNumber - 1, searchText = ViewBag.CurrentFilter })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
				else
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.PageNumber - 1 })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
			}
			else
			{
				if (ViewBag.CurrentFilter != null)
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.totalPages, searchText = ViewBag.CurrentFilter })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
				else
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.totalPages })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
			}

			<li>
				<a href="@Url.Action("Index", new { page = 1, searchText = ViewBag.CurrentFilter })">
					<i class="fas fa-home"></i>
				</a>
			</li>

			@if (ViewBag.PageNumber < ViewBag.totalPages)
			{
				<li>
					<a href="@Url.Action("Index", new { page = ViewBag.PageNumber + 1, searchText = ViewBag.CurrentFilter })">
						<i class="fa-solid fa-angle-right"></i>
					</a>
				</li>
			}
			else
			{
				<li>
					<a href="@Url.Action("Index", new { page = 1, searchText = ViewBag.CurrentFilter })">
						<i class="fa-solid fa-angle-right"></i>
					</a>
				</li>
			}
		</ul>
	}
</div>

<div>
	<a class="estilo_boton_lista btn btn-secondary" href="@Url.Action("Index", "Home")">
		<i class="fa fa-undo" aria-hidden="true"></i>


	</a>
</div>