Ventas_Vehiculos/Ventas_Vehiculos/Controllers/ComprasController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ventas_Vehiculos.Models;
using PagedList.Mvc;

namespace Ventas_Vehiculos.Controllers
{
    public class ComprasController : Controller
    {
        private DB_VehiculosEntities3 db = new DB_VehiculosEntities3();

        // GET: Compras
        public ActionResult Index()
        {
            var tBL_Compra = db.TBL_Compra.Include(t => t.TBL_Anno).Include(t => t.TBL_Capacidad).Include(t => t.TBL_Color).Include(t => t.TBL_Disenno).Include(t => t.TBL_Marca).Include(t => t.TBL_Modelo).Include(t => t.TBL_Motor).Include(t => t.TBL_Usuario).Include(t => t.TBL_Usuario1).Include(t => t.TBL_Vehiculo);
            return View(tBL_Compra.ToList());
        }


		[HttpGet]
		public ActionResult Index(string marcaFiltro, int? page)
		{
			ViewBag.MarcasSelect = new SelectList(db.TBL_Marca.OrderBy(m => m.TC_Descripcion), "TN_IdMarca", "TC_Descripcion");

			var compras = db.TBL_Compra.Include(c => c.TBL_Vehiculo)
									   .Include(c => c.TBL_Marca)
									   .OrderBy(c => c.TBL_Marca.TC_Descripcion);

			if (!string.IsNullOrEmpty(marcaFiltro) && marcaFiltro != "0")
			{
				int marcaId = int.Parse(marcaFiltro);
				compras = (IOrderedQueryable<TBL_Compra>)compras.Where(c => c.TBL_Marca.TN_IdMarca == marcaId);
			}

			int pageSize = 10;
			int pageNumber = (page ?? 1);
			ViewBag.PageNumber = pageNumber;
			int totalItems = compras.Count();
			int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
			ViewBag.totalPages = totalPages;

			var orderedCompras = compras.ToList(); // Obtener todos los datos ordenados antes de la paginación
			var pagedCompras = orderedCompras.ToPagedList(pageNumber, pageSize);

			ViewBag.CurrentFilter = marcaFiltro;

			return View(pagedCompras);
		}

		// GET: Compras/Details/5
		public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_Compra tBL_Compra = db.TBL_Compra.Find(id);
            if (tBL_Compra == null)
            {
                return HttpNotFound();
            }
            return View(tBL_Compra);
        }


		// GET: Compras/Create
		public ActionResult Create()
        {
			ViewBag.TN_IdAnno = GetSortedSelectList(db.TBL_Anno, "TN_IdAnno", "TC_Descripcion");
			ViewBag.TN_IdCapacidad = GetSortedSelectList(db.TBL_Capacidad, "TN_IdCapacidad", "TC_Descripcion");
			ViewBag.TN_IdColor = GetSortedSelectList(db.TBL_Color, "TN_IdColor", "TC_Descripcion");
			ViewBag.TN_IdDisenno = GetSortedSelectList(db.TBL_Disenno, "TN_IdDisenno", "TC_Descripcion");
			ViewBag.TN_IdMarca = GetSortedSelectList(db.TBL_Marca, "TN_IdMarca", "TC_Descripcion");
			ViewBag.TN_IdModelo = GetSortedSelectList(db.TBL_Modelo, "TN_IdModelo", "TC_Descripcion");
			ViewBag.TN_IdMotor = GetSortedSelectList(db.TBL_Motor, "TN_IdMotor", "TC_Descripcion");
			ViewBag.TN_IdUsuario = new SelectList(db.TBL_Usuario, "TN_IdUsuario", "TN_IdUsuario");
			ViewBag.TN_IdVehiculo = new SelectList(db.TBL_Vehiculo, "TN_IdVehiculo", "TN_IdVehiculo");
			return View();
        }
		private SelectList GetSortedSelectList<T>(IEnumerable<T> source, string valueField, string textField)
		{
			var sortedList = source.OrderBy(item => item.GetType().GetProperty(textField).GetValue(item, null))
								   .Select(item => new SelectListItem
								   {
									   Value = item.GetType().GetProperty(valueField).GetValue(item, null).ToString(),
									   Text = item.GetType().GetProperty(textField).GetValue(item, null).ToString()
								   })
								   .ToList();
			return new SelectList(sortedList, "Value", "Text");
		}

		// POST: Compras/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TN_IdCompra,TN_IdVehiculo,TN_Cantidad,TN_IdMarca,TN_IdModelo,TN_IdCapacidad,TN_IdColor,TN_IdAnno,TN_IdMotor,TN_IdDisenno,TN_IdUsuario")] TBL_Compra tBL_Compra)
        {
            if (ModelState.IsValid)
            {
                db.TBL_Compra.Add(tBL_Compra);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TN_IdAnno = new SelectList(db.TBL_Anno, "TN_IdAnno", "TC_Descripcion", tBL_Compra.TN_IdAnno);
            ViewBag.TN_IdCapacidad = new SelectList(db.TBL_Capacidad, "TN_IdCapacidad", "TC_Descripcion", tBL_Compra.TN_IdCapacidad);
            ViewBag.TN_IdColor = new SelectList(db.TBL_Color, "TN_IdColor", "TC_Descripcion", tBL_Compra.TN_IdColor);
            ViewBag.TN_IdDisenno = new SelectList(db.TBL_Disenno, "TN_IdDisenno", "TC_Descripcion", tBL_Compra.TN_IdDisenno);
            ViewBag.TN_IdMarca = new SelectList(db.TBL_Marca, "TN_IdMarca", "TC_Descripcion", tBL_Compra.TN_IdMarca);
            ViewBag.TN_IdModelo = new SelectList(db.TBL_Modelo, "TN_IdModelo", "TC_Descripcion", tBL_Compra.TN_IdModelo);
            ViewBag.TN_IdMotor = new SelectList(db.TBL_Motor, "TN_IdMotor", "TC_Descripcion", tBL_Compra.TN_IdMotor);
            ViewBag.TN_IdUsuario = new SelectList(db.TBL_Usuario, "TN_IdUsuario", "TN_IdUsuario", tBL_Compra.TN_IdUsuario);
            ViewBag.TN_IdVehiculo = new SelectList(db.TBL_Vehiculo, "TN_IdVehiculo", "TN_IdVehiculo", tBL_Compra.TN_IdVehiculo);
            return View(tBL_Compra);
        }

		// GET: Compras/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			TBL_Compra tBL_Compra = db.TBL_Compra.Find(id);
			if (tBL_Compra == null)
			{
				return HttpNotFound();
			}

			// Get related data
			ViewBag.TN_IdUsuario = new SelectList(db.TBL_Usuario, "TN_IdUsuario", "TN_IdUsuario", tBL_Compra.TN_IdUsuario);
			ViewBag.TN_IdVehiculo = new SelectList(db.TBL_Vehiculo, "TN_IdVehiculo", "TN_IdVehiculo", tBL_Compra.TN_IdVehiculo);

			ViewBag.TN_IdAnno = GetSortedSelectList(db.TBL_Anno, "TN_IdAnno", "TC_Descripcion", tBL_Compra.TN_IdAnno);
			ViewBag.TN_IdCapacidad = GetSortedSelectList(db.TBL_Capacidad, "TN_IdCapacidad", "TC_Descripcion", tBL_Compra.TN_IdCapacidad);
			ViewBag.TN_IdColor = GetSortedSelectList(db.TBL_Color, "TN_IdColor", "TC_Descripcion", tBL_Compra.TN_IdColor);
			ViewBag.TN_IdDisenno = GetSortedSelectList(db.TBL_Disenno, "TN_IdDisenno", "TC_Descripcion", tBL_Compra.TN_IdDisenno);
			ViewBag.TN_IdMarca = GetSortedSelectList(db.TBL_Marca, "TN_IdMarca", "TC_Descripcion", tBL_Compra.TN_IdMarca);
			ViewBag.TN_IdModelo = GetSortedSelectList(db.TBL_Modelo, "TN_IdModelo", "TC_Descripcion", tBL_Compra.TN_IdModelo);
			ViewBag.TN_IdMotor = GetSortedSelectList(db.TBL_Motor, "TN_IdMotor", "TC_Descripcion", tBL_Compra.TN_IdMotor);


			return View(tBL_Compra);
		}



		// Agrega esta función en tu controlador para ordenar las listas de selección
		private SelectList GetSortedSelectList<T>(IEnumerable<T> source, string valueField, string textField, object selectedValue = null)
		{
			var sortedList = source.OrderBy(item => item.GetType().GetProperty(textField).GetValue(item, null))
								   .Select(item => new SelectListItem
								   {
									   Value = item.GetType().GetProperty(valueField).GetValue(item, null).ToString(),
									   Text = item.GetType().GetProperty(textField).GetValue(item, null).ToString(),
									   Selected = (selectedValue != null && item.GetType().GetProperty(valueField).GetValue(item, null).ToString() == selectedValue.ToString())
								   })
								   .ToList();
			return new SelectList(sortedList, "Value", "Text");
		}


		// POST: Compras/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to, for 
		// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit([Bind(Include = "TN_IdCompra,TN_IdVehiculo,TN_Cantidad,TN_IdMarca,TN_IdModelo,TN_IdCapacidad,TN_IdColor,TN_IdAnno,TN_IdMotor,TN_IdDisenno,TN_IdUsuario")] TBL_Compra tBL_Compra)
		{
			if (ModelState.IsValid)
			{
				db.Entry(tBL_Compra).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			// Get related data
			ViewBag.TN_IdUsuario = new SelectList(db.TBL_Usuario, "TN_IdUsuario", "TN_Nombre", tBL_Compra.TN_IdUsuario);
			ViewBag.TN_IdVehiculo = new SelectList(db.TBL_Vehiculo, "TN_IdVehiculo", "TN_Placa", tBL_Compra.TN_IdVehiculo);

			ViewBag.TN_IdAnno = GetSortedSelectList(db.TBL_Anno, "TN_IdAnno", "TC_Descripcion", tBL_Compra.TN_IdAnno);
			ViewBag.TN_IdCapacidad = GetSortedSelectList(db.TBL_Capacidad, "TN_IdCapacidad", "TC_Descripcion", tBL_Compra.TN_IdCapacidad);
			ViewBag.TN_IdColor = GetSortedSelectList(db.TBL_Color, "TN_IdColor", "TC_Descripcion", tBL_Compra.TN_IdColor);
			ViewBag.TN_IdDisenno = GetSortedSelectList(db.TBL_Disenno, "TN_IdDisenno", "TC_Descripcion", tBL_Compra.TN_IdDisenno);
			ViewBag.TN_IdMarca = GetSortedSelectList(db.TBL_Marca, "TN_IdMarca", "TC_Descripcion", tBL_Compra.TN_IdMarca);
			ViewBag.TN_IdModelo = GetSortedSelectList(db.TBL_Modelo, "TN_IdModelo", "TC_Descripcion", tBL_Compra.TN_IdModelo);
			ViewBag.TN_IdMotor = GetSortedSelectList(db.TBL_Motor, "TN_IdMotor", "TC_Descripcion", tBL_Compra.TN_IdMotor);


			return View(tBL_Compra);
		}       // GET: Compras/Delete/5
		public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TBL_Compra tBL_Compra = db.TBL_Compra.Find(id);
            if (tBL_Compra == null)
            {
                return HttpNotFound();
            }
            return View(tBL_Compra);
        }

        // POST: Compras/Delete/5

Ventas_Vehiculos/Ventas_Vehiculos/Views/Compras/Create.cshtml
@model Ventas_Vehiculos.Models.TBL_Compra

@{
	ViewBag.Title = "Nueva compra";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />

<h2 class="titulo_create">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal  letra_tabla letra_form">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdVehiculo, "Número del vehículo", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdVehiculo", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdVehiculo, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_Cantidad, "Cantidad comprada", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.TN_Cantidad, new { htmlAttributes = new { @class = "form-control", @required = true, @placeholder="Escribe cantidad" } })
				@Html.ValidationMessageFor(model => model.TN_Cantidad, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdMarca, "Marca", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdMarca", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdMarca, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdModelo, "Modelo", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdModelo", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdModelo, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdCapacidad, "Capacidad", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdCapacidad", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdCapacidad, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdColor, "Color", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdColor", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdColor, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdAnno, "Año", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdAnno", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdAnno, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdMotor, "Motor", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdMotor", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdMotor, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TN_IdDisenno, "Diseño del vehículo", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdDisenno", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TN_IdDisenno, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group letra_search">
			@Html.LabelFor(model => model.TBL_Usuario.TN_IdUsuario, "Cédula del cliente", htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.DropDownList("TN_IdUsuario", null, htmlAttributes: new { @class = "form-control" })
				@Html.ValidationMessageFor(model => model.TBL_Usuario.TN_IdUsuario, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button type="submit" class="btn btn-secondary btn_create">
					<i class="fa fa-plus"></i>
					
				</button>

			</div>
		</div>
	</div>
}

<div>
	<a class="estilo_boton_lista btn btn-secondary" href="@Url.Action("Index", "Compras")">
		<i class="fa fa-undo" aria-hidden="true"></i>
		

	</a>
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Compras/Details.cshtml
@model Ventas_Vehiculos.Models.TBL_Compra

@{
    ViewBag.Title = "Detalles compra";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="titulo_details">@ViewBag.Title</h2>

<div>
	<hr />
	<dl class="dl-horizontal letra_search letra_tabla">

		<dt class="titulo_details_tabla">
			Número del vehículo
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Vehiculo.TN_IdVehiculo)
			
		</dd>

		<dt class="titulo_details_tabla">
			Cantidad comprada
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TN_Cantidad)
			
		</dd>

		<dt class="titulo_details_tabla">
			Marca
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Marca.TC_Descripcion)
			
		</dd>

		<dt class="titulo_details_tabla">
			Modelo
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Modelo.TC_Descripcion)
			
		</dd>

		<dt class="titulo_details_tabla">
			Capacidad
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Capacidad.TC_Descripcion)
			
		</dd>

		<dt class="titulo_details_tabla">
			Color
		</dt>
		<dd>
			
				@Html.DisplayFor(model => model.TBL_Color.TC_Descripcion)
			
		</dd>
		<dt class="titulo_details_tabla">
			Año
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Anno.TC_Descripcion)
			
		</dd>

		<dt class="titulo_details_tabla">
			Motor
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Motor.TC_Descripcion)
			
		</dd>



		<dt class="titulo_details_tabla">
			Diseño del vehículo
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Disenno.TC_Descripcion)
			
		</dd>


		<dt class="titulo_details_tabla">
			Cédula de cliente
		</dt>

		<dd>
			
				@Html.DisplayFor(model => model.TBL_Usuario.TN_IdUsuario)
			
		</dd>



	</dl>
</div>
<p>
	<a class="btn btn-secondary editar btn-separator" href="@Url.Action("Edit","Compras",  new { id = Model.TN_IdCompra } )">
		<i class="fa-solid fa-pen-to-square">

		</i>
		
	</a>

	<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Compras")">
		<i class="fa fa-undo"></i>
		
	</a>
</p>

Ventas_Vehiculos/Ventas_Vehiculos/Views/Compras/Edit.cshtml
@model Ventas_Vehiculos.Models.TBL_Compra

@{
	ViewBag.Title = "Actualizando compra";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="titulo_edit">@ViewBag.Title</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal letra_tabla letra_search letra_form">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.TN_IdCompra)

	<!-- DropDownList para Número del Vehículo -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdVehiculo, "Número del vehículo", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> vehiculosList = ViewBag.TN_IdVehiculo as List<SelectListItem>;
			}

			@Html.DropDownList("TN_IdVehiculo", vehiculosList, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdVehiculo, "", new { @class = "text-danger" })
		</div>
	</div>


	<div class="form-group">
		@Html.LabelFor(model => model.TN_Cantidad, "Cantidad comprada", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.TN_Cantidad, new { htmlAttributes = new { @class = "form-control", placeholder = "Digite la cantidad comprada", @required = true } })
			<br />
			@Html.ValidationMessageFor(model => model.TN_Cantidad, "Completa este campo", new { @class = "text-danger" })
		</div>
	</div>

	<!-- DropDownList para Marca -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdMarca, "Marca", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> marcasList = ViewBag.TN_IdMarca as List<SelectListItem>;

			}


			@Html.DropDownListFor(model => model.TN_IdMarca, marcasList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdMarca, "", new { @class = "text-danger" })
		</div>
	</div>


	<!-- DropDownList para Modelo -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdModelo, "Modelo", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> modelosList = ViewBag.TN_IdModelo as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdModelo, modelosList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdModelo, "", new { @class = "text-danger" })
		</div>
	</div>

	<!-- DropDownList para Capacidad -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdCapacidad, "Capacidad", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> capacidadesList = ViewBag.TN_IdCapacidad as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdCapacidad, capacidadesList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdCapacidad, "", new { @class = "text-danger" })
		</div>
	</div>

	<!-- DropDownList para Color -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdColor, "Color", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> coloresList = ViewBag.TN_IdColor as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdColor, coloresList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdColor, "", new { @class = "text-danger" })
		</div>
	</div>

	<!-- DropDownList para Año -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdAnno, "Año", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> annosList = ViewBag.TN_IdAnno as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdAnno, annosList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdAnno, "", new { @class = "text-danger" })
		</div>
	</div>

	<!-- DropDownList para Motor -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdMotor, "Motor", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> motoresList = ViewBag.TN_IdMotor as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdMotor, motoresList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdMotor, "", new { @class = "text-danger" })
		</div>
	</div>


	<!-- DropDownList para Diseño del vehículo -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdDisenno, "Diseño del vehículo", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> disennosList = ViewBag.TN_IdDisenno as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdDisenno, disennosList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdDisenno, "", new { @class = "text-danger" })
		</div>
	</div>


	<!-- DropDownList para Cédula del cliente -->
	<div class="form-group">
		@Html.LabelFor(model => model.TN_IdUsuario, "Cédula del cliente", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@{
				List<SelectListItem> usuariosList = ViewBag.TN_IdUsuario as List<SelectListItem>;
			}
			@Html.DropDownListFor(model => model.TN_IdUsuario, usuariosList, new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.TN_IdUsuario, "", new { @class = "text-danger" })
		</div>
	</div>


	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<button type="submit" class="btn btn-secondary editar">
				<i class="fa fa-refresh" aria-hidden="true"></i>

			</button>

		</div>
	</div>
</div>

	}


	<div>
		<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Compras")">
			<i class="fa fa-undo"></i>

		</a>
	</div>

	@section Scripts {
		@Scripts.Render("~/bundles/jqueryval")
	}