Ventas_Vehiculos/Ventas_Vehiculos/Controllers/DisennosController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ventas_Vehiculos.Models;

namespace Ventas_Vehiculos.Controllers
{
    public class DisennosController : Controller
    {
		private DB_VehiculosEntities3 db = new DB_VehiculosEntities3();
		// GET: Disennos
		public ActionResult Index()
        {
            return View(db.TBL_Disenno.ToList());
        }


		[HttpGet]
		public ActionResult Index(int? page, string searchText)
		{

			int pageSize = 10;
			int pageNumber = (page ?? 1);
			ViewBag.PageNumber = pageNumber;
			IEnumerable<TBL_Disenno> disennos;

			disennos = db.TBL_Disenno.AsQueryable();

			if (!string.IsNullOrEmpty(searchText))
			{
				disennos = disennos.Where(m => m.TC_Descripcion.Contains(searchText));
			}
			int totalItems = disennos.Count(); // Cantidad total de elementos
			int totalPages = (int)Math.Ceiling((double)totalItems / pageSize); // Cálculo de total de páginas
			ViewBag.totalPages = totalPages;

			ViewBag.CurrentFilter = searchText;

			var disennosOrdenadas = disennos.OrderBy(m => m.TC_Descripcion);
			var disennosPaginas = disennosOrdenadas.Skip((pageNumber - 1) * pageSize).Take(pageSize);


			return View(disennosPaginas);
			//return View(marcasOrdenadas.ToList());
			// Paginate the marcas

		}


		// GET: Disennos/Details/5
		public ActionResult Details(int id)
        {
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			TBL_Disenno disenno = db.TBL_Disenno.Find(id);
			if (disenno == null)
			{
				return HttpNotFound();
			}
			return View(disenno);
		}

        // GET: Disennos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Disennos/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "TN_idDisenno, TC_Descripcion")] TBL_Disenno disenno)
        {
			if (ModelState.IsValid)
			{
				db.TBL_Disenno.Add(disenno);
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(disenno);
		}

        // GET: Disennos/Edit/5
        public ActionResult Edit(int id)
        {
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			TBL_Disenno disenno = db.TBL_Disenno.Find(id);
			if (disenno == null)
			{
				return HttpNotFound();
			}
			return View(disenno);
		}

        // POST: Disennos/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "TN_idDisenno, TC_Descripcion")] TBL_Disenno disenno)
        {
			if (ModelState.IsValid)
			{
				db.Entry(disenno).State = EntityState.Modified;
				db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(disenno);
		}

        // GET: Disennos/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Disennos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Disennos/Create.cshtml
@model Ventas_Vehiculos.Models.TBL_Disenno

@{
	ViewBag.Title = "Nuevo diseño";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/Site.css" rel="stylesheet" />

<h2 class="titulo_create">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal letra_form letra_tabla">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group letra_search">
			<label class="titulo_details_tabla control-label col-md-2">Diseño</label>
			<div class="col-md-10">
				@Html.EditorFor(model => model.TC_Descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe diseño", @required = true } })
				@Html.ValidationMessageFor(model => model.TC_Descripcion, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button type="submit" class="btn btn-secondary btn_create">
					<i class="fa fa-plus"></i>
					
				</button>
			</div>
		</div>
	</div>
}

<div>
	<a class="estilo_boton_lista btn btn-secondary" href="@Url.Action("Index", "Disennos")">
		<i class="fa fa-undo" aria-hidden="true"></i>
		

	</a>
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Disennos/Details.cshtml
@model Ventas_Vehiculos.Models.TBL_Disenno

@{
	ViewBag.Title = "Detalles diseño";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="titulo_details">@ViewBag.Title</h2>

<div>
	<hr />
	<dl class="dl-horizontal letra_tabla letra_search">
		<dt>
			Diseño
		</dt>

		<dd>
		
				@Html.DisplayFor(model => model.TC_Descripcion)
			
		</dd>

	</dl>
</div>
<p>
	
		<a class="btn btn-secondary editar btn-separator" href="@Url.Action("Edit","Disennos",  new { id = Model.TN_IdDisenno } )">
			<i class="fa-solid fa-pen-to-square">

			</i>
			
		</a>

		<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Disennos")">
			<i class="fa fa-undo"></i>
			
		</a>
	
</p>

Ventas_Vehiculos/Ventas_Vehiculos/Views/Disennos/Edit.cshtml
@model Ventas_Vehiculos.Models.TBL_Disenno

@{
	ViewBag.Title = "Actualizando diseño";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="titulo_edit">@ViewBag.Title</h2>


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal letra_form letra_tabla">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		@Html.HiddenFor(model => model.TN_IdDisenno)

		<div class="form-group letra_search">
			<label class="titulo_details_tabla control-label col-md-2">Diseño</label>
			<div class="col-md-10">
				@Html.EditorFor(model => model.TC_Descripcion, new { htmlAttributes = new { @class = "form-control", placeholder = "Escribe diseño", @required = true } })
				<br />
				@Html.ValidationMessageFor(model => model.TC_Descripcion, "Completa este campo", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<button type="submit" class="btn btn-secondary editar">
					<i class="fa fa-refresh" aria-hidden="true"></i>
					
				</button>
			</div>
		</div>
	</div>
}

<div>
	<a class="btn btn-secondary estilo_boton_lista btn-separator" href="@Url.Action("Index", "Disennos")">
		<i class="fa fa-undo"></i>
		
	</a>
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

Ventas_Vehiculos/Ventas_Vehiculos/Views/Disennos/Index.cshtml
@model IEnumerable<Ventas_Vehiculos.Models.TBL_Disenno>

@{
	ViewBag.Title = "Diseños";
	Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 class="titulo_index">@ViewBag.Title</h2>


<p>
	<a class="btn btn-secondary btn_create" href="@Url.Action("Create","Disennos")">
		<i class="fa fa-plus" aria-hidden="true"></i>

	</a>
</p>

@using (Html.BeginForm("Index", "Disennos", FormMethod.Get))
{
	<div class="form-group letra_search">
		@Html.Label("Filtrar por diseño")
		@Html.TextBox("searchText", ViewBag.CurrentFilter as string, new { @class = "form-control", @required = true, @placeholder = "Escribe diseño" })
		<button type="submit" class="btn btn-secondary btn_search btn-separator">
			<i class="fa-solid fa-search"></i>
		</button>
		<a href="@Url.Action("Index", "Disennos")" class="btn btn-secondary btn_clean ">
			<i class="fa-solid fa-eraser"></i>
		</a>
	</div>
}
<div class="cuadro_tabla">
	<table class="table letra_tabla table-bordered table-hover">
		<tr class="titulo_encabezado_tabla">
			<th class="titulo_encabezado_tabla">
				Diseños
			</th>
			<th class="titulo_encabezado_tabla" colspan="2">
				Operaciones
			</th>
		</tr>
		<tbody class="table letra_tabla table-bordered table-hover">
			@foreach (var item in Model)
			{
				<tr class="datos_tabla table-hover">
					<td>

						@Html.DisplayFor(modelItem => item.TC_Descripcion)

					</td>
					<td>

						<a class="btn btn-secondary editar btn-separator" href="@Url.Action("Edit","Disennos", new { id = item.TN_IdDisenno })">
							<i class="fa-solid fa-pen-to-square"></i>

						</a>
						<a class="btn btn-secondary detallado btn-separator" href="@Url.Action("Details","Disennos", new { id = item.TN_IdDisenno })">
							<i class="fa-solid fa-circle-info"></i>

						</a>

					</td>
				</tr>
			}
		</tbody>
	</table>
</div>

<!-- Resto del código anterior -->
@if (ViewBag.CurrentFilter != null && Model.Any())
{

}

@if (Model.Any())
{
	<div class="current-page-info datos_paginacion">
		Página @ViewBag.PageNumber de @ViewBag.totalPages
	</div>
}

<div class="pagination-container datos_paginacion">
	@if (Model.Any())
	{
		<ul class="pagination">
			@if (ViewBag.PageNumber > 1)
			{
				if (ViewBag.CurrentFilter != null)
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.PageNumber - 1, searchText = ViewBag.CurrentFilter })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
				else
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.PageNumber - 1 })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
			}
			else
			{
				if (ViewBag.CurrentFilter != null)
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.totalPages, searchText = ViewBag.CurrentFilter })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
				else
				{
					<li>
						<a href="@Url.Action("Index", new { page = ViewBag.totalPages })">
							<i class="fa-solid fa-angle-left"></i>
						</a>
					</li>
				}
			}

			<li>
				<a href="@Url.Action("Index", new { page = 1, searchText = ViewBag.CurrentFilter })">
					<i class="fas fa-home"></i>
				</a>
			</li>

			@if (ViewBag.PageNumber < ViewBag.totalPages)
			{
				<li>
					<a href="@Url.Action("Index", new { page = ViewBag.PageNumber + 1, searchText = ViewBag.CurrentFilter })">
						<i class="fa-solid fa-angle-right"></i>
					</a>
				</li>
			}
			else
			{
				<li>
					<a href="@Url.Action("Index", new { page = 1, searchText = ViewBag.CurrentFilter })">
						<i class="fa-solid fa-angle-right"></i>
					</a>
				</li>
			}
		</ul>
	}
</div>

<div>
	<a class="estilo_boton_lista btn btn-secondary" href="@Url.Action("Index", "Home")">
		<i class="fa fa-undo" aria-hidden="true"></i>


	</a>
</div>